enum ClientEmitEventTypes {
  CHANGE_SECTION = "CHANGE_SECTION",
  CURSOR_POSITION = "CURSOR_POSITION",
  DISCONNECT = "DISCONNECT",
  GET_COMPOSITION_OR_NOTE_REQUEST = "GET_COMPOSITION_OR_NOTE_REQUEST",
  SET_AGENT_STATE = "SET_AGENT_STATE",
  SPEECH_CONFIG = "SPEECH_CONFIG",
  SPEECH_END = "SPEECH_END",
  SPEECH_START = "SPEECH_START",
  SPEECH_TRANSFER = "SPEECH_TRANSFER",
  SUBMIT_COMPOSITION_REQUEST = "SUBMIT_COMPOSITION_REQUEST",
  USER_REQUEST = "USER_REQUEST"
}

export { ClientEmitEventTypes };
