enum S2ErrorTypes {
  DEFAULT = "DEFAULT",
  ERROR_ADD_SECTION = "ERROR_ADD_SECTION",
  ERROR_COPY_FORWARD = "ERROR_COPY_FORWARD",
  ERROR_CREATE_NOTE = "ERROR_CREATE_NOTE",
  ERROR_DELETE_NOTE = "ERROR_DELETE_NOTE",
  ERROR_DELETE_SECTION = "ERROR_DELETE_SECTION",
  ERROR_FETCH_NOTE = "ERROR_FETCH_NOTE",
  ERROR_NOTES_PULL = "ERROR_NOTES_PULL",
  ERROR_SCRIPT_CHANGE = "ERROR_SCRIPT_CHANGE"
}

export { S2ErrorTypes };
