const EVENT_TYPES = {
  SECTION_RESPONSE: {
    ADD: "ADD",
    COPY_FORWARD_SECTION: "COPY_FORWARD_SECTION",
    DELETE: "DELETE",
    NO_MATCHING_SECTION_FOUND_FOR_MACRO: "NO_MATCHING_SECTION_FOUND_FOR_MACRO",
    NO_SECTION_IN_FOCUS_FOR_ANY_SECTION_MACRO: "NO_SECTION_IN_FOCUS_FOR_ANY_SECTION_MACRO",
    SCRIPT_CHANGE_SECTION: "SCRIPT_CHANGE_SECTION",
    SCRIPT_INSERT: "SCRIPT_INSERT",
    SECTION_FORMATTED: "SECTION_FORMATTED",
    UNDO_DELETE_THIS_UPDATE: "UNDO_DELETE_THIS_UPDATE",
    UPDATE: "UPDATE"
  },
  SERVER_RESPONSE: {
    FAILURE: "FAILURE",
    NEW: "NEW",
    SUCCESS: "SUCCESS",
    UPDATED: "UPDATED"
  }
};

export default EVENT_TYPES;
