const DICTATION_URL_ENDPOINTS: { [key: string]: any } = {
  MS_DICTATION_ENDPOINT: process.env.MS_DICTATION_ENDPOINT,
  MS_SUKI_ASR_ENDPOINT: process.env.MS_SUKI_ASR_ENDPOINT,
  MS_SUKI_SERVER_ENDPOINT: process.env.MS_SUKI_SERVER_ENDPOINT
};

export { DICTATION_URL_ENDPOINTS };
