import { OOBE_TASKS, OOBE_TASKS_NON_INTEGRATED, TASK_STATUSES } from "../../constants";

const OOBE_TASKS_STATUS_STATE = {
  [OOBE_TASKS.ASK_SUKI_HELP]: TASK_STATUSES.PENDING,
  [OOBE_TASKS.NOTES_COMPLETION]: TASK_STATUSES.PENDING,
  [OOBE_TASKS.PATIENTS_ICON_CLICK]: TASK_STATUSES.PENDING,
  [OOBE_TASKS.PLAY_DEMO]: TASK_STATUSES.PENDING,
  [OOBE_TASKS.TOGGLE_AGENT]: TASK_STATUSES.PENDING
};

const OOBE_TASKS_STATUS_STATE_NON_INTEGRATED = {
  [OOBE_TASKS.PLAY_DEMO]: TASK_STATUSES.PENDING,
  [OOBE_TASKS.TOGGLE_AGENT]: TASK_STATUSES.PENDING,
  [OOBE_TASKS_NON_INTEGRATED.CREATE_A_NOTE]: TASK_STATUSES.PENDING,
  [OOBE_TASKS_NON_INTEGRATED.DOWNLOAD_MOBILE_APP]: TASK_STATUSES.PENDING,
  [OOBE_TASKS_NON_INTEGRATED.GET_HELP]: TASK_STATUSES.PENDING,
  [OOBE_TASKS_NON_INTEGRATED.IMPORT_SCHEDULE]: TASK_STATUSES.PENDING,
  [OOBE_TASKS_NON_INTEGRATED.INSTALL_SUKI_WINDOWS]: TASK_STATUSES.PENDING
};

const oobeTasksList = [
  OOBE_TASKS.TOGGLE_AGENT,
  OOBE_TASKS.PLAY_DEMO,
  OOBE_TASKS.ASK_SUKI_HELP,
  OOBE_TASKS.PATIENTS_ICON_CLICK,
  OOBE_TASKS.NOTES_COMPLETION
];

const oobeTasksListNonIntegrated = [
  OOBE_TASKS_NON_INTEGRATED.CREATE_A_NOTE,
  OOBE_TASKS_NON_INTEGRATED.INSTALL_SUKI_WINDOWS,
  OOBE_TASKS_NON_INTEGRATED.DOWNLOAD_MOBILE_APP,
  OOBE_TASKS_NON_INTEGRATED.IMPORT_SCHEDULE,
  OOBE_TASKS_NON_INTEGRATED.GET_HELP
];

export { OOBE_TASKS_STATUS_STATE, OOBE_TASKS_STATUS_STATE_NON_INTEGRATED, oobeTasksList, oobeTasksListNonIntegrated };
