enum SignUpFormFields {
  AGREEMENT = "AGREEMENT",
  EMAIL = "EMAIL",
  EMR = "EMR",
  FIRST_NAME = "FIRST_NAME",
  LAST_NAME = "LAST_NAME",
  ORGANIZATION_NAME = "ORGANIZATION_NAME",
  PHONE_NUMBER = "PHONE_NUMBER",
  SPECIALTY = "SPECIALTY",
  SUFFIX = "SUFFIX"
}

export { SignUpFormFields };
