enum S2Views {
  DIAGNOSIS_VIEW = "DIAGNOSIS_VIEW",
  HELP = "HELP",
  INVALID_VIEW = "INVALID_VIEW",
  NOTE = "NOTE",
  PROFILE = "PROFILE",
  SCHEDULE = "SCHEDULE",
  SCRIPT = "SCRIPT",
  SECTION_TRANSCRIPT = "SECTION_TRANSCRIPT",
  SUBMISSION_PANEL = "SUBMISSION_PANEL",
  WELCOME = "WELCOME",
  UNFINISHED_NOTES = "UNFINISHED_NOTES"
}

export { S2Views };
