const s2SourceTypes = {
  ASR_GOOGLE: "ASR_GOOGLE",
  ASR_HOMEGROWN: "ASR_HOMEGROWN",
  ASR_NVOQ: "ASR_NVOQ",
  ASR_TRANSCRIPT: "asr_transcript",
  COPY_FORWARD: "COPY_FORWARD",
  DEFAULT: "default",
  DOCTOR_TYPED: "doctor_typed",
  DYNAMIC_VITALS: "DYNAMIC_VITALS",
  DYNAMIC_VITALS_TEMPLATE: "DYNAMIC_VITALS_TEMPLATE",
  INTERMEDIATE_TEXT: "INTERMEDIATE_TEXT",
  NONE: "none",
  NOTE_PULL: "NOTE_PULL",
  NOTETYPE_PREFILLED: "NOTETYPE_PREFILLED",
  OPS_TO_PROCESS: "ops_to_process",
  OPS_TYPED: "ops_typed",
  PREPOPULATED: "prepopulated",
  SCRIPT: "SCRIPT",
  SCRIPT_CHANGE: "SCRIPT_CHANGE",
  SCRIPT_CONTENT: "script_content",
  TYPED_ADMIN: "TYPED_ADMIN",
  TYPED_DOCTOR: "TYPED_DOCTOR",
  TYPED_SCRIBE: "TYPED_SCRIBE",
  UNKNOWN: "UNKNOWN"
};

type s2SourceType =
  | "ASR_GOOGLE"
  | "ASR_HOMEGROWN"
  | "ASR_NVOQ"
  | "COPY_FORWARD"
  | "DYNAMIC_VITALS"
  | "DYNAMIC_VITALS_TEMPLATE"
  | "INTERMEDIATE_TEXT"
  | "NOTE_PULL"
  | "NOTETYPE_PREFILLED"
  | "SCRIPT"
  | "SCRIPT_CHANGE"
  | "TYPED_ADMIN"
  | "TYPED_DOCTOR"
  | "TYPED_SCRIBE"
  | "UNKNOWN";

export { s2SourceTypes, s2SourceType };
