const DYNAMIC_CHIP_MAPPING: { [key: string]: string } = {
  "A1C": "HEMOGLOBIN_A1C",
  "ALP": "ALKALINE_PHOSPHATASE",
  "ALT": "ALANINE_AMINOTRANSFERASE",
  "AST": "ASPARTATE_AMINOTRANSFERASE",
  "Age": "AGE",
  "Albumin": "ALBUMIN",
  "Allergies": "ALLERGIES",
  "BMI": "BMI",
  "BUN": "UREA",
  "Blood Pressure": "BLOOD_PRESSURE",
  "CO2": "CARBON_DIOXIDE",
  "CT Narrative": "CT_NARRATIVE",
  "Chief Complaint": "CHIEF_COMPLAINT",
  "Chloride": "CHLORIDE",
  "Creatinine": "CREATININE",
  "Current Medications": "CURRENT_MEDICATION",
  "Default": "DEFAULT",
  "DirectBilirubin": "BILIRUBIN_DIRECT",
  "First Name": "FIRST_NAME",
  "Gender": "GENDER",
  "Glucose": "GLUCOSE",
  "HDLCholesterol": "CHOLESTEROL_HDL",
  "Heart Rate": "HEART_RATE",
  "Height": "HEIGHT",
  "Hematocrit": "HEMATOCRIT",
  "Hemoglobin": "HEMOGLOBIN",
  "INR": "INR",
  "LDLCholesterol": "CHOLESTEROL_LDL",
  "Last Name": "LAST_NAME",
  "MRI Narrative": "MRI_NARRATIVE",
  "PSA": "PROSTATE_ANTIGEN",
  "Past Medical History": "PAST_MEDICAL_HISTORY",
  "Past Surgical History": "PAST_SURGICAL_HISTORY",
  "Platelets": "PLATELETS",
  "Potassium": "POTASSIUM",
  "Protein": "PROTEIN",
  "Pulse Oximetry": "PULSE_OXIMETRY",
  "RBC": "ERYTHROCYTES",
  "Respiratory Rate": "RESPIRATORY_RATE",
  "Show Past Medical History": "PAST_MEDICAL_HISTORY_SHOW_ME",
  "Show Past Surgical History": "PAST_SURGICAL_HISTORY_SHOW_ME",
  "Sodium": "SODIUM",
  "TSH": "THYROTROPIN",
  "Temperature": "TEMPERATURE",
  "Thyroxine": "THYROXINE",
  "TotalBilirubin": "BILIRUBIN_TOTAL",
  "TotalCholesterol": "TOTAL_CHOLESTEROL",
  "Triglycerides": "TRIGLYCERIDES",
  "WBC": "LEUKOCYTES",
  "Weight": "WEIGHT",
  "XRAY Narrative": "XRAY_NARRATIVE"
};

export { DYNAMIC_CHIP_MAPPING };
