enum Specialities {
  NA = "NA",
  ALLERGY_AND_IMMUNOLOGY = "ALLERGY_AND_IMMUNOLOGY",
  ANESTHESIOLOGY = "ANESTHESIOLOGY",
  CARDIOLOGY = "CARDIOLOGY",
  CRITICAL_CARE = "CRITICAL_CARE",
  DERMATOLOGY = "DERMATOLOGY",
  EMERGENCY_MEDICINE = "EMERGENCY_MEDICINE",
  ENDOCRINOLOGY = "ENDOCRINOLOGY",
  FAMILY_MEDICINE = "FAMILY_MEDICINE",
  GASTROENTEROLOGY = "GASTROENTEROLOGY",
  GENETICS = "GENETICS",
  HEMATOLOGY = "HEMATOLOGY",
  INFECTIOUS_DISEASE = "INFECTIOUS_DISEASE",
  INTERNAL_MEDICINE = "INTERNAL_MEDICINE",
  MEDICAL_ONCOLOGY = "MEDICAL_ONCOLOGY",
  NEPHROLOGY = "NEPHROLOGY",
  NEUROLOGY = "NEUROLOGY",
  NEUROSURGERY = "NEUROSURGERY",
  NUCLEAR_MEDICINE = "NUCLEAR_MEDICINE",
  OBSTETRICS_GYNECOLOGY = "OBSTETRICS_GYNECOLOGY",
  OPHTHALMOLOGY = "OPHTHALMOLOGY",
  ORTHOPEDIC_SURGERY = "ORTHOPEDIC_SURGERY",
  OTOLARYNGOLOGY_HEAD_AND_NECK = "OTOLARYNGOLOGY_HEAD_AND_NECK",
  PALLIATIVE_MEDICINE = "PALLIATIVE_MEDICINE",
  PAIN_MANAGEMENT = "PAIN_MANAGEMENT",
  PATHOLOGY = "PATHOLOGY",
  PEDIATRICS = "PEDIATRICS",
  PHYSICAL_MEDICINE_AND_REHABILITATION = "PHYSICAL_MEDICINE_AND_REHABILITATION",
  PLASTIC_SURGERY = "PLASTIC_SURGERY",
  PODIATRY = "PODIATRY",
  PREVENTATIVE_MEDICINE = "PREVENTATIVE_MEDICINE",
  PSYCHIATRY = "PSYCHIATRY",
  PULMONOLOGY = "PULMONOLOGY",
  RADIATION_ONCOLOGY = "RADIATION_ONCOLOGY",
  RADIOLOGY_DIAGNOSTIC = "RADIOLOGY_DIAGNOSTIC",
  RADIOLOGY_INTERVENTIONAL = "RADIOLOGY_INTERVENTIONAL",
  RHEUMATOLOGY = "RHEUMATOLOGY",
  SPORTS_MEDICINE = "SPORTS_MEDICINE",
  SURGERY_CARDIAC_AND_THORACIC = "SURGERY_CARDIAC_AND_THORACIC",
  SURGERY_COLON_AND_RECTAL = "SURGERY_COLON_AND_RECTAL",
  SURGERY_GENERAL = "SURGERY_GENERAL",
  SURGERY_PEDIATRIC = "SURGERY_PEDIATRIC",
  SURGERY_VASCULAR = "SURGERY_VASCULAR",
  UROLOGY = "UROLOGY",
  UNLISTED_MEDICAL = "UNLISTED_MEDICAL",
  UNLISTED_SURGICAL = "UNLISTED_SURGICAL"
}

const SpecialitiesLabels = {
  [Specialities.NA]: "NA",
  [Specialities.ALLERGY_AND_IMMUNOLOGY]: "Allergy / Immunology",
  [Specialities.ANESTHESIOLOGY]: "Anesthesiology",
  [Specialities.CARDIOLOGY]: "Cardiology",
  [Specialities.CRITICAL_CARE]: "Critical Care",
  [Specialities.DERMATOLOGY]: "Dermatology",
  [Specialities.EMERGENCY_MEDICINE]: "Emergency Medicine",
  [Specialities.ENDOCRINOLOGY]: "Endocrinology",
  [Specialities.FAMILY_MEDICINE]: "Family Medicine",
  [Specialities.GASTROENTEROLOGY]: "Gastroenterology",
  [Specialities.GENETICS]: "Genetics",
  [Specialities.HEMATOLOGY]: "Hematology",
  [Specialities.INFECTIOUS_DISEASE]: "Infectious Disease",
  [Specialities.INTERNAL_MEDICINE]: "Internal Medicine",
  [Specialities.MEDICAL_ONCOLOGY]: "Medical Oncology",
  [Specialities.NEPHROLOGY]: "Nephrology",
  [Specialities.NEUROLOGY]: "Neurology",
  [Specialities.NEUROSURGERY]: "Neurosurgery",
  [Specialities.NUCLEAR_MEDICINE]: "Nuclear Medicine",
  [Specialities.OBSTETRICS_GYNECOLOGY]: "Obstetrics Gynecology",
  [Specialities.OPHTHALMOLOGY]: "Ophthalmology",
  [Specialities.ORTHOPEDIC_SURGERY]: "Orthopedic Surgery",
  [Specialities.OTOLARYNGOLOGY_HEAD_AND_NECK]: "Otolaryngology - Head and Neck",
  [Specialities.PALLIATIVE_MEDICINE]: "Palliative Medicine",
  [Specialities.PAIN_MANAGEMENT]: "Pain Management",
  [Specialities.PATHOLOGY]: "Pathology",
  [Specialities.PEDIATRICS]: "Pediatrics",
  [Specialities.PHYSICAL_MEDICINE_AND_REHABILITATION]: "Physical Medicine and Rehabilitation",
  [Specialities.PLASTIC_SURGERY]: "Plactic Surgery",
  [Specialities.PODIATRY]: "Podiatry",
  [Specialities.PREVENTATIVE_MEDICINE]: "Preventative Medicine",
  [Specialities.PSYCHIATRY]: "Psychiatry",
  [Specialities.PULMONOLOGY]: "Pulmonology",
  [Specialities.RADIATION_ONCOLOGY]: "Radiation Oncology",
  [Specialities.RADIOLOGY_DIAGNOSTIC]: "Radiology - Diagnostic",
  [Specialities.RADIOLOGY_INTERVENTIONAL]: "Radiology - Interventional",
  [Specialities.RHEUMATOLOGY]: "Rheumatology",
  [Specialities.SPORTS_MEDICINE]: "Sports Medicine",
  [Specialities.SURGERY_CARDIAC_AND_THORACIC]: "Surgery - Cardiac and Thoracic",
  [Specialities.SURGERY_COLON_AND_RECTAL]: "Surgery - Colon and Rectal",
  [Specialities.SURGERY_GENERAL]: "Surgery - General",
  [Specialities.SURGERY_PEDIATRIC]: "Surgery - Pediatric",
  [Specialities.SURGERY_VASCULAR]: "Surgery - Vascular",
  [Specialities.UROLOGY]: "Urology",
  [Specialities.UNLISTED_MEDICAL]: "Unlisted Medical",
  [Specialities.UNLISTED_SURGICAL]: "Unlisted Surgical"
};

export { Specialities, SpecialitiesLabels };
