const SUKI_X_TEST_DEV_ORGANIZATION_ID = "dbbcb937-e91f-46cb-89d7-39cd96787d55";

const SUKI_X_TEST_DEV_USER_ID = "fefda702-466f-4cbf-9876-0d753600932";

enum USER_FORM_FIELD {
  AGREEMENT = "AGREEMENT",
  EMAIL = "EMAIL",
  EMR = "EMR",
  FIRST_NAME = "FIRST_NAME",
  LAST_NAME = "LAST_NAME",
  ORGANIZATION_NAME = "ORGANIZATION_NAME",
  PHONE_NUMBER = "PHONE_NUMBER",
  ROLE = "ROLE",
  SPECIALTY = "SPECIALTY"
}

const SPECIALTY_TYPE = {
  NA: "NA",
  ALLERGY_AND_IMMUNOLOGY: "ALLERGY_AND_IMMUNOLOGY",
  ANESTHESIOLOGY: "ANESTHESIOLOGY",
  CARDIOLOGY: "CARDIOLOGY",
  CRITICAL_CARE: "CRITICAL_CARE",
  DERMATOLOGY: "DERMATOLOGY",
  EMERGENCY_MEDICINE: "EMERGENCY_MEDICINE",
  ENDOCRINOLOGY: "ENDOCRINOLOGY",
  FAMILY_MEDICINE: "FAMILY_MEDICINE",
  GASTROENTEROLOGY: "GASTROENTEROLOGY",
  GENETICS: "GENETICS",
  HEMATOLOGY: "HEMATOLOGY",
  INFECTIOUS_DISEASE: "INFECTIOUS_DISEASE",
  INTERNAL_MEDICINE: "INTERNAL_MEDICINE",
  MEDICAL_ONCOLOGY: "MEDICAL_ONCOLOGY",
  NEPHROLOGY: "NEPHROLOGY",
  NEUROLOGY: "NEUROLOGY",
  NEUROSURGERY: "NEUROSURGERY",
  NUCLEAR_MEDICINE: "NUCLEAR_MEDICINE",
  OBSTETRICS_GYNECOLOGY: "OBSTETRICS_GYNECOLOGY",
  OPHTHALMOLOGY: "OPHTHALMOLOGY",
  ORTHOPEDIC_SURGERY: "ORTHOPEDIC_SURGERY",
  OTOLARYNGOLOGY_HEAD_AND_NECK: "OTOLARYNGOLOGY_HEAD_AND_NECK",
  PALLIATIVE_MEDICINE: "PALLIATIVE_MEDICINE",
  PAIN_MANAGEMENT: "PAIN_MANAGEMENT",
  PATHOLOGY: "PATHOLOGY",
  PEDIATRICS: "PEDIATRICS",
  PHYSICAL_MEDICINE_AND_REHABILITATION: "PHYSICAL_MEDICINE_AND_REHABILITATION",
  PLASTIC_SURGERY: "PLASTIC_SURGERY",
  PODIATRY: "PODIATRY",
  PREVENTATIVE_MEDICINE: "PREVENTATIVE_MEDICINE",
  PSYCHIATRY: "PSYCHIATRY",
  PULMONOLOGY: "PULMONOLOGY",
  RADIATION_ONCOLOGY: "RADIATION_ONCOLOGY",
  RADIOLOGY_DIAGNOSTIC: "RADIOLOGY_DIAGNOSTIC",
  RADIOLOGY_INTERVENTIONAL: "RADIOLOGY_INTERVENTIONAL",
  RHEUMATOLOGY: "RHEUMATOLOGY",
  SPORTS_MEDICINE: "SPORTS_MEDICINE",
  SURGERY_CARDIAC_AND_THORACIC: "SURGERY_CARDIAC_AND_THORACIC",
  SURGERY_COLON_AND_RECTAL: "SURGERY_COLON_AND_RECTAL",
  SURGERY_GENERAL: "SURGERY_GENERAL",
  SURGERY_PEDIATRIC: "SURGERY_PEDIATRIC",
  SURGERY_VASCULAR: "SURGERY_VASCULAR",
  UROLOGY: "UROLOGY",
  UNLISTED_MEDICAL: "UNLISTED_MEDICAL",
  UNLISTED_SURGICAL: "UNLISTED_SURGICAL"
};

export { SPECIALTY_TYPE, SUKI_X_TEST_DEV_ORGANIZATION_ID, SUKI_X_TEST_DEV_USER_ID, USER_FORM_FIELD };
