const EMR_TYPE = {
  ALLSCRIPTS: "ALLSCRIPTS",
  ATHENA: "ATHENA",
  CERNER: "CERNER",
  ECLINICALWORKS: "ECLINICALWORKS",
  ELATION: "ELATION",
  EPIC: "EPIC",
  GREENWAY: "GREENWAY",
  MEDITECH: "MEDITECH",
  MIRTH: "MIRTH",
  NEXTGEN: "NEXTGEN",
  UNKNOWN: "UNKNOWN"
};

const EMR_SECONDARY_TYPE = {
  ALLSCRIPTS_PROFESSIONAL_EMR: "ALLSCRIPTS_PROFESSIONAL_EMR",
  ALLSCRIPTS_TOUCHWORKS_EMR: "ALLSCRIPTS_TOUCHWORKS_EMR",
  ATHENA_EMR: "ATHENA_EMR",
  CERNER_EMR: "CERNER_EMR",
  ECW_EMR: "ECW_EMR",
  ELATION_EMR: "ELATION_EMR",
  EPIC_EMR: "EPIC_EMR",
  UNKNOWN_EMR: "UNKNOWN_EMR"
};

const TENANTS = {
  AMWELL: "Amwell"
};

export { EMR_SECONDARY_TYPE, EMR_TYPE, TENANTS };
