enum MacrosTagType {
  DEFAULT,
  MACRO_TYPE,
  MACRO_TAG,
  BLOCK_TAG,
  MACRO_NAME
}

const SCRIPT_TAG = {
  BLOCK: "BLOCK_TAG",
  NAME: "MACRO_NAME",
  TAG: "MACRO_TAG",
  TYPE: "MACRO_TYPE"
};

const DYNAMIC_VITALS_TEMPLATE = "DYNAMIC_VITALS_TEMPLATE";

export { DYNAMIC_VITALS_TEMPLATE, MacrosTagType, SCRIPT_TAG };
