enum IntroScreens {
  Screen1 = "screen1",
  Screen2 = "screen2",
  Screen3 = "screen3",
  Screen4 = "screen4"
}

const OOBE_TASKS = {
  ASK_SUKI_HELP: "ASK_SUKI_HELP",
  NOTES_COMPLETION: "NOTES_COMPLETION",
  PATIENTS_ICON_CLICK: "PATIENTS_ICON_CLICK",
  PLAY_DEMO: "PLAY_DEMO",
  TOGGLE_AGENT: "TOGGLE_AGENT"
};

const OOBE_TASKS_NON_INTEGRATED = {
  CREATE_A_NOTE: "CREATE_A_NOTE",
  DOWNLOAD_MOBILE_APP: "DOWNLOAD_MOBILE_APP",
  GET_HELP: "GET_HELP",
  IMPORT_SCHEDULE: "IMPORT_SCHEDULE",
  INSTALL_SUKI_WINDOWS: "INSTALL_SUKI_WINDOWS"
};

export { IntroScreens, OOBE_TASKS, OOBE_TASKS_NON_INTEGRATED };
