import i18n from "i18next";

const ANY_SECTION = {
  id: "11111111-1111-1111-1111-111111111111",
  createdBy: "11111111-1111-1111-1111-111111111111",
  name: i18n.t("modals.scriptDetails.anySectionDictation")
};

const COMPOSITION_REQUEST_TYPE = {
  COMPOSITION: "Composition",
  NOTE: "Note"
};

const USER_REQUEST_TYPE = {
  ADD_SECTION: "ADD_SECTION",
  ATTACH_PATIENT: "ATTACH_PATIENT",
  CANCEL_CREATE_NOTE: "CANCEL_CREATE_NOTE",
  CLICK_INSERT_SCRIPT: "CLICK_INSERT_SCRIPT",
  CLICK_NOTES_PULL: "CLICK_NOTES_PULL",
  CLICK_REFRESH_VITALS_ON_SCREEN: "CLICK_REFRESH_VITALS_ON_SCREEN",
  COMPOSITION_SUBMISSION_SUCCESSFUL: "COMPOSITION_SUBMISSION_SUCCESSUFL",
  CREATE_NOTE: "CREATE_NOTE",
  CREATE_NOTE_WITH_NOTETYPE: "CREATE_NOTE_WITH_NOTETYPE",
  CREATE_NOTE_WITH_NOTETYPE_PATIENT: "CREATE_NOTE_WITH_NOTETYPE_PATIENT",
  DELETE_SECTION: "DELETE_SECTION",
  SAVE_COMPOSITION_TO_UNFINISHED: "SAVE_COMPOSITION_TO_UNFINISHED",
  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  UPDATE_SECTION: "UPDATE_SECTION"
};

const SUBMISSION_WARNING = {
  ENCOUNTER_NOT_OPEN: "ENCOUNTER_NOT_OPEN",
  NO_ENCOUNTER: "NO_ENCOUNTER",
  NO_LAB_RESULTS: "NO_LAB_RESULTS",
  NO_VALID_OB_EPISODE: "NO_VALID_OB_EPISODE",
  UNKNOWN: "UNKNOWN",
  UNKNOWN_PATIENT: "UNKNOWN_PATIENT"
};

enum SuggestionTypes {
  ED = "ED",
  PL = "PL"
}

enum CardType {
  ALLERGIES = "ALLERGIES",
  CURRENT_MEDICATION = "CURRENT_MEDICATION",
  PAST_MEDICAL_HISTORY = "PAST_MEDICAL_HISTORY",
  PAST_MEDICAL_HISTORY_SHOW_ME = "PAST_MEDICAL_HISTORY_SHOW_ME",
  PAST_SURGICAL_HISTORY = "PAST_SURGICAL_HISTORY",
  PAST_SURGICAL_HISTORY_SHOW_ME = "PAST_SURGICAL_HISTORY_SHOW_ME",
  VITALS = "VITALS"
}

enum NoteActionType {
  ADD_NEW_PROBLEM,
  DELETE_PROBLEM_SECTION,
  HTML_SECTION_FOCUS,
  INSERT_SCRIPT,
  PROBLEM_SECTION_DELETE,
  PROBLEM_SECTION_FOCUS,
  SAVE_TO_UNFINISHED_NOTES,
  SECTION_BLUR,
  SECTION_FOCUS,
  TAB_NAVIGATION,
  UNDO,
  UPDATE_CURSOR_POSITION,
  UPDATE_PROBLEM_SECTION,
  UPDATE_SCRIPT_MODULE,
  UPDATE_SECTION,
  UPDATE_UNDERSCORE_OCCURANCES
}

const VITAL_SIGNS = {
  BLOOD_PRESSURE: "Blood Pressure",
  BMI: "Body Mass Index",
  HEART_RATE: "Heart Rate",
  HEIGHT: "Height",
  RESPIRATORY_RATE: "Respiratory Rate",
  PULSE: "Pulse Oximetry",
  TEMPERATURE: "Temperature",
  WEIGHT: "Weight"
};

const TIME_TO_REFRESH_VITALS = 5000;

export {
  ANY_SECTION,
  CardType,
  COMPOSITION_REQUEST_TYPE,
  NoteActionType,
  SUBMISSION_WARNING,
  SuggestionTypes,
  TIME_TO_REFRESH_VITALS,
  USER_REQUEST_TYPE,
  VITAL_SIGNS
};
