const LOADING_STATUSES = {
  ERROR: "error",
  LOADED: "loaded",
  LOADING: "loading",
  NOT_LOADED: "not loaded"
};

const TASK_STATUSES = {
  COMPLETED: "COMPLETED",
  PENDING: "PENDING"
};

const PROBLEM_STATUSES = {
  CONFIRMED: "CONFIRMED",
  UNCONFIRMED: "UNCONFIRMED",
  UNKNOWN: "UNKNOWN"
};

const ERROR_CODES = {
  CLOSE: "CLOSE"
};

export { ERROR_CODES, LOADING_STATUSES, PROBLEM_STATUSES, TASK_STATUSES };
