enum WindowsEmitEventTypes {
  CREATE_NEW_SESSION = "CREATE_NEW_SESSION",
  STOP_DICTATION = "STOP_DICTATION",
  START_DICTATION = "START_DICTATION",
  SPEECH_TRANSFER = "SPEECH_TRANSFER",
  TERMINATE_SESSION = "TERMINATE_SESSION",
  UPDATE_ACCESS_TOKEN = "UPDATE_ACCESS_TOKEN"
}

export { WindowsEmitEventTypes };
