enum WindowsReceiveEventTypes {
  INTENT = "INTENT",
  DICTATION_CONNECTION_CLOSE = "DICTATION_CONNECTION_CLOSE",
  DICTATION_CONNECTION_CLOSE_FAILURE = "DICTATION_CONNECTION_CLOSE_FAILURE",
  DICTATION_CONNECTION_FAILURE = "DICTATION_CONNECTION_FAILURE",
  DICTATION_CONNECTION_SUCCESS = "DICTATION_CONNECTION_SUCCESS"
}

export { WindowsReceiveEventTypes };
